apiVersion: apps/v1
kind: Deployment
metadata:
  name: lung-cancer-prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lung-cancer-prediction
  template:
    metadata:
      labels:
        app: lung-cancer-prediction
    spec:
      containers:
      - name: lung-cancer-prediction
        image: gcr.io/lung-cancer-prediction-1/myapp:v1
        ports:
        - containerPort: 5000