artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_file_path: '/Users/mansipandya/Desktop/cancerData.csv'

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/cancerData.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/cancerData.csv